coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: false
    patch: false
    changes: false

comment:
  layout: "header, diff, changes, tree"
  behavior: default

ignore:
  - "local"
  - "nmz_opt_lib"
  - "test"
