dist: xenial

language: cpp

compiler: gcc

addons:
  apt:
    packages:
      - libgmp-dev
      - libomp-dev # for OpenMP support in clang
      - libmpfr-dev
      - libflint-dev

matrix:
  include:
    - env: BUILDSYSTEM=makedistcheck NO_COVERAGE=1
    - env: BUILDSYSTEM=eantic-nauty-cocoa-extended
    - env: BUILDSYSTEM=eantic-cocoa NO_OPENMP=yes
    - env: BUILDSYSTEM=nauty NO_OPENMP=yes
      compiler: clang
    - env: BUILDSYSTEM=flint-cocoa
      compiler: clang
#    - env: BUILDSYSTEM=eantic-nauty
#      os: osx
#      osx_image: xcode10.2
#      compiler: clang
#    ## Test on Mac OS X with LLVM from Homebrew for OpenMP support
#    ## Build "static" Mac binary distribution and deploy to Normaliz-bindist
#    ## (thus we set  NO_COVERAGE=1)
#    - env: BUILDSYSTEM=cocoa-eantic-nauty-static CONFIGURE_FLAGS=--enable-openmp NO_COVERAGE=1
#      os: osx
#       compiler: clang
#       addons:
#        homebrew:
#          update: true
#          packages:
#            llvm
#       before_install:
#         - LLVMDIR="$(brew --prefix)/opt/llvm"
#         - export PATH="${LLVMDIR}/bin/:$PATH"
#         - export LDFLAGS="-L${LLVMDIR}/lib -Wl,-rpath,${LLVMDIR}/lib"
#       after_success:
#         - ./.make-bindist.sh  
#     - env: BUILDSYSTEM=nauty
#       os: osx
#      osx_image: xcode7.3
#      compiler: clang

branches:
  except:
    - gh-pages

script: ./.travis-build.sh

after_script:
  - rm -rf local nmz_opt_lib
  - bash <(curl -s https://codecov.io/bash)
