dist: xenial

language: cpp

compiler: gcc

addons:
  apt:
    packages:
      - libgmp-dev
      - libomp-dev # for OpenMP support in clang

matrix:
  include:
    - env: BUILDSYSTEM=autotools-makedistcheck
    - env: BUILDSYSTEM=autotools-enfnormaliz-nauty
    - env: BUILDSYSTEM=autotools-enfnormaliz-nmzintegrate CONFIGURE_FLAGS="--disable-openmp"
    - env: BUILDSYSTEM=autotools-nauty
    - env: BUILDSYSTEM=autotools CONFIGURE_FLAGS="--disable-openmp"
    - env: BUILDSYSTEM=autotools-flint-nmzintegrate-nauty
    - env: BUILDSYSTEM=autotools-enfnormaliz-nauty  # again but with clang
      compiler: clang
    - env: BUILDSYSTEM=autotools-flint-nmzintegrate
      compiler: clang
    - env: BUILDSYSTEM=autotools-enfnormaliz-nauty
      os: osx
      osx_image: xcode10.2
      compiler: clang
    - env: BUILDSYSTEM=autotools-flint-nmzintegrate
      os: osx
      osx_image: xcode9.2
      compiler: clang
    ## Test on Mac OS X with LLVM from Homebrew for OpenMP support
    ## Build "static" Mac binary distribution and deploy to Normaliz-bindist
    - env: BUILDSYSTEM=autotools-nmzintegrate-enfnormaliz-nauty-static CONFIGURE_FLAGS=--enable-openmp
      os: osx
      compiler: clang
      addons:
        homebrew:
          update: true
          packages:
            llvm
      before_install:
       - LLVMDIR="$(brew --prefix)/opt/llvm"
       - export PATH="${LLVMDIR}/bin/:$PATH"
       - export LDFLAGS="-L${LLVMDIR}/lib -Wl,-rpath,${LLVMDIR}/lib"
      after_success:
       - ./.make-bindist.sh  
    - env: BUILDSYSTEM=autotools
      os: osx
      osx_image: xcode8.3
      compiler: clang
    - env: BUILDSYSTEM=autotools-nauty-makedistcheck
      os: osx
      osx_image: xcode7.3
      compiler: clang

branches:
  except:
    - gh-pages

script: ./.travis-build.sh
